# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

defaults: &defaults
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  encoding: unicode
  pool: 25
  username: postgres
  password: postgres

development:
  <<: *defaults
  database: friendly_proje_mangae_dev

test: &test
  <<: *defaults
  database: friendly_proje_mangae_test